// client/src/components/Nav.vue
<template>
  <nav class="navbar is-primary" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <img src="../assets/logo.png" height="28">
      <h3 class="title">Be Happy</h3>
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" :class="{'is-active': isActive }" @click="isActive = !isActive" >
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div class="navbar-menu " :class="{'is-active': isActive }">
    <div class="navbar-start">
      <router-link class="navbar-item is-tab" to="/" active-class="is-active" exact>
        Home
      </router-link>

      <router-link class="navbar-item is-tab" to="/feed" active-class="is-active">
        Feed
      </router-link>

      <router-link class="navbar-item is-tab" to="/about" active-class="is-active">
        Documentation
      </router-link>

      <div class="navbar-item has-dropdown is-hoverable" >
        <a class="navbar-link" >
          More
        </a>

        <div class="navbar-dropdown">
          <router-link class="navbar-item is-tab" to="about" active-class="is-active">
            About
          </router-link>
          <a class="navbar-item">
            Jobs
          </a>
          <a class="navbar-item">
            Contact
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item">
            Report an issue
          </a>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <login-badge />
      </div>
    </div>
  </div>
</nav>

</template>

<script>
import LoginBadge from './LoginBadge';

export default {
    data(){
        return {
            isActive: false
        }
    },
    components: {
        LoginBadge,
    }
}
</script>

<style>

</style>

// react-app/src/components/Nav.js
import React from 'react';
//import LoginBadge from './LoginBadge';

export default function Nav() {

  const data = { isActive: false }

  return (
  <nav className="navbar is-primary" role="navigation" aria-label="main navigation">
  <div className="navbar-brand">
    <a className="navbar-item" href="https://bulma.io">
      <img src="../assets/logo.png" height="28" />
      <h3 className="title">Be Happy</h3>
    </a>

    <a role="button" className="navbar-burger" aria-label="menu" aria-expanded="false" className="{'is-active': isActive }" click="isActive = !isActive" >
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div className="navbar-menu " className="{'is-active': isActive }">
    <div className="navbar-start">
      <router-link className="navbar-item is-tab" to="/" active-className="is-active" exact>
        Home
      </router-link>

      <router-link className="navbar-item is-tab" to="/feed" active-className="is-active">
        Feed
      </router-link>

      <router-link className="navbar-item is-tab" to="/about" active-className="is-active">
        Documentation
      </router-link>

      <div className="navbar-item has-dropdown is-hoverable" >
        <a className="navbar-link" >
          More
        </a>

        <div className="navbar-dropdown">
          <router-link className="navbar-item is-tab" to="about" active-className="is-active">
            About
          </router-link>
          <a className="navbar-item">
            Jobs
          </a>
          <a className="navbar-item">
            Contact
          </a>
          <hr className="navbar-divider" />
          <a className="navbar-item">
            Report an issue
          </a>
        </div>
      </div>
    </div>

    <div className="navbar-end">
      <div className="navbar-item">
        <login-badge />
      </div>
    </div>
  </div>
</nav>
)}
